[[inbound]]
protocol = "vless"
uuid = "0fbf4f81-2598-4b6a-a623-0ead4cb9efa9"
path = "/vless"

[[inbound]]
protocol = "vmess"
uuid = "0fbf4f81-2598-4b6a-a623-0ead4cb9efa9"
path = "/vmess"

[[inbound]]
protocol = "trojan"
path = "/trojan"
password = "Strong|Pass"

[outbound]
addresses = []
port = 0
protocol = "Freedom"
match = []
